### ISSUE TITLE
QOL stuff

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#104]
1- Kill Sounds should be enabled for games with points or portalgoal or bed or breakgoal.
2- firecharge and tnt can be directly used when bed gamerule is enabled allowing you to create fireball fight.
    - Fireball should only break wood and wool
    - customizable kb for fireball
    - fireball doesn't damage shooter but it damages opponent by 2 hearts
    - tnt breaks endstone wool and wood
3- /nospeed command only works in boxing that removes speed effect
4- add soup kit where right clicking soup heals player by 3.5 hearts and dropped bowls are removed from ground immediately
5- menu customization is going to take some time so in the meantime why not give us a simple feature that allows us to select kit menu size and next page button

**Comment by HierarchyMan** [comment]
@GoodestEnglish More stuff
- killing/dying shouldnt actually kill you it should set to spectator or respawn with heal instead of sending kill packet to player
- leaving queue and doing stuff like that shouldnt just teleport you to spawn

**Comment by HierarchyMan** [comment]
Also adding item to kit icon should remove all attributes like enchantment names and effects and lore

**Comment by HierarchyMan** [comment]
There should be premade presets for some famous kits when making one

**Comment by GoodestEnglish** [comment]
Ok so there's a lot, implement all of them needs a lot of time. Here's the priority order I will finish first to last (From top to bottom, things which isn't in the list will not be implemented right now).

- nospeed command
- soup heals 3.5 hearts
- remove leave queue send to spawn
- fireball and tnt customizeable

I believe no one will create more then 54 kits right now, so I dont think point 5 is needed right now
Not too sure what does number 6 means. May you please explain more?
About point 8, you should not set kit icon with edited item, you should get a fresh item.
Premade presets is what I've think for a while. But since KitGameRules are not stable yet. It is better to use discussions premade kit first.

**Comment by HierarchyMan** [comment]
About point 8
If I use a splash potion as icon it shows instant health when I browse kits which shouldn't happen

**Comment by GoodestEnglish** [comment]
Added the first 3 in the latest update

**Comment by HierarchyMan** [comment]
every change is working as intended and placeholders are working just fine
If you loose on MMC it doesn't kill you it kinda vanishes you for the other player
Same goes for dying in void, it doesn't even damage you when u die in void it simply marks you as dead and sets you to spectator
Also in some matches after dying respawn screen shows up and no matter how many times I click respawn it doesn't let me
So I want you to make these changes

**Comment by GoodestEnglish** [comment]
Currently it does vanish you when you get killed. The death animation is from packet, which shouldn't affect anything.

I believe the respawn screen is a 1.8 spigot bug. I've tried to avoid not use Player#spigot#respawn method due to this. But i will keep an eye to see if there's a way to fix it.

**Comment by GoodestEnglish** [comment]
> About point 8
> If I use a splash potion as icon it shows instant health when I browse kits which shouldn't happen
> And about point 6 please give me some time I will make a video

This happens because the potion has a thing we called "ItemFlag". To fix this, I've added a new command called /toggleitemflag. You can pickup a fresh potion, hold the potion, and use command "/toggleitemflag HIDE_POTION_EFFECTS". This command will remove the potion effects text from the item. After that just simply set the new item to the kit icon.

**Comment by Chromaah** [comment]
Hi, I have some more suggestions that I think could make the plugin more professional. I did not want to open another issue for these suggestions so ill put them here.

- Add customizable 'Victory' titles and 'Game over'/'You lost' titles.

- Make the '<player> Scored' chat message when someone scores also a title.

> **Chromaah** scored!
    **1** - **0**
          
- Start Freeze is a bit glitchy, when you move while getting spawned it glitches out, and sometimes gets flagged by my anticheat as flight (in bridge and such), so maybe make it so it completely freezes them, or make it so that its not as buggy.

- maybe add an option to make the item in item.yml execute a custom command (custom menu flexibility)

- add a /leave or /l command option, or maybe make it so its available in unranked or specific kits

**Comment by GoodestEnglish** [comment]
I could add those except for custom command, I am still thinking how I should implement it (But it is going to be soon!)

But at the same time could you please explain what do you mean by start freeze is a bit glitchy? I would like to see a video to see how it happens. Thank you.

**Comment by Chromaah** [comment]
Cool! adding those titles can really give the server a more professional look.

Start Freeze is glitchy for me atleast, in bridge it kinda like lags you back and forth, i will send a video as soon as i can

**Comment by Chromaah** [comment]
https://imgur.com/a/N13dt7h

**Comment by GoodestEnglish** [comment]
Can't really do anything in this situation. The player gets teleported back because they are trying to move out from the spawn and since start freeze is enabled, the system tries to teleport the player back. 

There's one solution on my head: currently the player will get tp to "spawn location + 1 y axis" when respawn, this is because it looks more smooth (popular servers like hypixel and lunar are doing like this).

I would like to also hear what do you mean by "glitches out"?

**Comment by Chromaah** [comment]
> Can't really do anything in this situation. The player gets teleported back because they are trying to move out from the spawn and since start freeze is enabled, the system tries to teleport the player back.

Oh I see, how does minemen do it? I see it's a bit different

> There's one solution on my head: remove the system which currently the player will get tp to "spawn location + 1 y axis" when respawn, this is because it looks more smooth (popular servers like hypixel and lunar are doing like this).

That could work

> I would like to also hear what do you mean by "glitches out"?

I meant like it glitches the screen making it look like shown in the video

**Comment by GoodestEnglish** [comment]
Are you pressing W when the glitch  is happening?

**Comment by GoodestEnglish** [comment]
> > Can't really do anything in this situation. The player gets teleported back because they are trying to move out from the spawn and since start freeze is enabled, the system tries to teleport the player back.
> 
> 
> 
> Oh I see, how does minemen do it? I see it's a bit different
> 
> 
> 
> > There's one solution on my head: remove the system which currently the player will get tp to "spawn location + 1 y axis" when respawn, this is because it looks more smooth (popular servers like hypixel and lunar are doing like this).
> 
> 
> 
> That could work
> 
> 
> 
> > I would like to also hear what do you mean by "glitches out"?
> 
> 
> 
> I meant like it glitches the screen making it look like shown in the video

I am not sure how mmc does it. I don't play mmc, I mainly play lunar 😅

**Comment by Chromaah** [comment]
> Are you pressing W when the glitch is happening?

sometimes i am, but other times it just happens like that even if i dont press anything

**Comment by GoodestEnglish** [comment]
I think I've found what happened. Will push a fix within a few days

**Comment by Chromaah** [comment]
Great!

**Comment by Chromaah** [comment]
oh! i also thought it could be cool to add something that damages you if you go too high above the limit (with ghost blocks) similar to minemen's or bedwarspractice.club's. In the future tho

**Comment by GoodestEnglish** [comment]
> oh! i also thought it could be cool to add something that damages you if you go too high above the limit (with ghost blocks) similar to minemen's or bedwarspractice.club's. In the future tho

I believe this is already implemented, the only difference is Eden will instant kill you.

**Comment by Chromaah** [comment]
oh, i see, maybe make it slowly do that? or maybe alert you 5 seconds before it does

**Comment by GoodestEnglish** [comment]
No point to do that because doing that might result some unexpected result. For example, people who cheats can load a lot of chunks in a short amount of time.

**Comment by Chromaah** [comment]
ah ok

**Comment by Chromaah** [comment]
> I think I've found what happened. Will push a fix within a few days

Are you gonna add the titles in the fix?

**Comment by GoodestEnglish** [comment]
Should be

**Comment by GoodestEnglish** [comment]
Fixed in latest update: https://github.com/diamond-rip/Eden/releases/tag/1.0.33-BETA-bbeb449

Fireball knockback customize will be in the next few updates

**Comment by Chromaah** [comment]
Its very smooth and the titles are clean! Thank you! :)
