### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#125]
1.better postmatch
![image](https://user-images.githubusercontent.com/40424128/216959737-80a3c0c3-dda6-4fc3-b87d-cf3ce07e9721.png)
2.Make 2 seconds wait to teleport to spawn when match end, 0 seconds it's shit.
3.Add events sumo,brackets
This all, i hope you make it.

**Comment by GoodestEnglish** [comment]
Please describe what do you mean by better post match.
I believe you updated the plugin. As I said in the new update: config.yml needs to be updated in this update. Please check in [here](https://github.com/diamond-rip/Eden/commit/bbeb449804686eb647f210e48d6c6f3762d52528#diff-58cdd3d308ccba6c594e040ff9c065bb11eeb6e30f35ba87694ea45d5ae6096c) and add those changed fields into your config.yml file. This update allows  player to customize the end duration. Since you didn't add those changed fields, the system will set the time to -1 which will instant end the match, also have a high chance to break things.
More events are def coming soon. But now I would like to mainly focus on bug fixing. Who wants to use a plugin which consistently contains bugs right?

**Comment by GoodestEnglish** [comment]
More specifically, you can customize the end duration in [config.yml](https://github.com/diamond-rip/Eden/blob/master/src/main/resources/config.yml#L66) line 66

**Comment by Mekvil** [comment]
like move arrmor up like on screen, and add blocked hits in sword stats

**Comment by GoodestEnglish** [comment]
I can add blocked hits. But the menu is not going to change. I don't want to fully copy what mmc has. This will just make the plugin with no unique things.

**Comment by Mekvil** [comment]
if you make limit blockhits and make it configurable it's gonna be great!

**Comment by Mekvil** [comment]
and add pls spectator messages in settings. To disable messages when someone start spectate

**Comment by Mekvil** [comment]
I mean if player reached blockhit limit - next blockhits don't gonna be register
