### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by ItzStormizn** [diamond-rip/Eden#237]
Can you please make Eden support MySQL please

**Comment by HierarchyMan** [comment]
I don't think it would be logical to add MySQL unless your server has plugins that exclusively require MySQL 
MySQL is still more widely known and used in the minecraft server community but adding it would prolly require a lot of time and effort.

**Comment by ItzStormizn** [comment]
> I don't think it would be logical to add MySQL unless your server has plugins that exclusively require MySQL MySQL is still more widely known and used in the minecraft server community but adding it would prolly require a lot of time and effort.

Most of the plugins in my server run on SQL. Pls add sql support.

**Comment by HierarchyMan** [comment]
Just use MySQL and mongodb together (it's possible)
It wouldn't be efficient to rewrite/write many lines of code just to add support for an inferior database system.
I think

**Comment by ItzStormizn** [comment]
> Just use MySQL and mongodb together (it's possible) It wouldn't be efficient to rewrite/write many lines of code just to add support for an inferior database system. I think

That's the issue. The VPS we are using is not able to support Mongo.

**Comment by GoodestEnglish** [comment]
MongoDB will not be added, at least for now. Due to:
- I am not too familiar with MySQL. MongoDB is my main working database.
- MongoDB are more user friendly, can transfer to JSON easily
- When store data on MySQL, you cannot store a list (technically you can in many ways, but tricky)
- Every MongoDB document are handled separately, meaning each document can store different datas.

MySQL is not bad, however the current Minecraft server mainstream are using MongoDB already (Such as Lunar, MMC). And I would highly recommend you to switch to MongoDB as soon as possible.

**Comment by HierarchyMan** [comment]
@ItzStormizn for now, try using eden without any db connections (disable it in config.yml).
Note that after you disable the db connections player data won't be saved and loaded plus stats and edited kits will reset when server is shut down. 
One thing you could do is use an external vps/host just for mongodb
Or if the server is only gonna be online when you're playing, you could try hosting mongodb directly from ur pc (it doesn't take more than 50mb or ram in the background).
