### ISSUE TITLE
a few more suggestions

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#25]
- ~~enabling instant golden apples doesn't give absorption hearts~~
- a GUI kit editor would be better than a kit editor with anvils and chests and signs
- ~~I find all kits storing in a database a little weird saving kits in yaml like arenas would be a great help~~
- ~~add portal protection per arena~~
- ~~add server IP below scoreboard by default~~
- an option to add glass panes in kit selection GUI
- parkour options for kits (iron plates= checkpoint golden plates=win)
- ~~force ending a game should say your stats won't be affected~~
- a chest randomizer for kits like Skywars
- ~~for some reason i cant add resistance to the effects of a kit (i could add speed and the others but not resistance)~~
- ~~and the stickfight/pearlfight game end issue we talked about~~

I know this is a lot to ask but these are just some of my suggestions that may help make this plugin a little better
And MLGrush works wonders by the way
your plugin is already the best on the internet and about to defeat other paid plugins very soon
keep up the good work
-cystol

**Comment by HierarchyMan** [comment]
Hope we get some info about events soon

**Comment by RealGoodestEnglish** [comment]
Instant golden apples should work, well, at least it works for me, could you provide a video explaining the issues maybe?
Here's my test result on instant golden apples:
https://user-images.githubusercontent.com/45838505/210075115-98fa24e4-5b2e-486b-b1d8-ed49cbabb286.mp4

I now understand what you mean by 'arena portal protection radius', I will add a settings for that soon

For now I will leave kit editor as right now, if I have extra time I might work on it, but no promise.

Kit in database is really weird. I did that because in my old practice server the plugin is running in multi-server. This will also change very soon.

Scoreboard is fully configurable. You can just add your server IP into each scoreboard in language.yml

Configurating kit selection GUI requires rework on Kit GUI. I will have it noted but it will not come soon.

Parkour options for kits is something what I wanted to do. This will also be added but it will not come soon since I want to make sure to have minimal bugs first. Stable is Eden first priority.

Chest randomizer is not going to add in Eden itself. If I ever make this out. This will be a separate addon plugin. But this will be my lowest priority because I believe stuff you mentioned above should be out first.

About force end, this is a good suggestion. I will make force end messages configurable soon.

stickfight/pearlfight should be fixed in latest update, let me know if you have any issues! (Just make sure you have points kit game rules enabled)

**Comment by HierarchyMan** [comment]
About the instant gap
The gap works fine but it doesnt give absorption effect
( Those 2 golden hearts ) 
Total hp 24

**Comment by RealGoodestEnglish** [comment]
What do you mean by "Saving it in a kit doesn't let me use it when I right click"?

**Comment by RealGoodestEnglish** [comment]
The golden head issue will be fixed soon.
I will make an option on the issues related to spleef, possibly.

**Comment by HierarchyMan** [comment]
When I right click nothing happens

**Comment by RealGoodestEnglish** [comment]
Do you mean right click the golden head?

**Comment by HierarchyMan** [comment]
Yes

**Comment by HierarchyMan** [comment]
and add absorption hearts to normal golden apples (when instant golden apple is enabled for kits like brigdes)
and i think the opponent team should get a point if point system is enabled and player just dies to void it own lava (it doesnt give any point for now and moves on)

**Comment by RealGoodestEnglish** [comment]
Noted. Will work on it soon

**Comment by RealGoodestEnglish** [comment]
Tested in my side and golden head works fine for me. May you try to test without any other plugins?

**Comment by HierarchyMan** [comment]
Sure I will try to test it as soon as I can

**Comment by HierarchyMan** [comment]
Also if you are planning on releasing a test server can I be staff?

**Comment by RealGoodestEnglish** [comment]
No plan on releasing a test server for now. Maybe if it gets a huge amount of requests.
