### ISSUE TITLE
can you make the queue menu like minemen?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#300]
![image](https://github.com/diamond-rip/Eden/assets/132185379/635612d3-a3dc-40ba-8b53-7c1c3a0c39bf)
![image](https://github.com/diamond-rip/Eden/assets/132185379/7a74c669-ee59-474b-9f56-da0d18258d00)

**Comment by serumanooo** [comment]
![2023-05-13_16 32 31](https://github.com/diamond-rip/Eden/assets/132185379/f554d45e-c13b-4c42-822c-7e4ec1b54ad9)
also, can you make a title when the player is respawning? if my memory is good, eden dont have this, the cooldown is in the chat, but i think a title is way better

**Comment by Chromaah** [comment]
yes, please add the respawn title, also i love making custom menus, so i made a really cool queue menu, the only problem is that i cant apply them to the items because i need to be able to execute custom commands with the items, so instead why not just add commands to lobby items, that way we can make our own menus

**Comment by serumanooo** [comment]
closed because i made a list
