### ISSUE TITLE
Bugs and some more suggestions

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#312]
Suggestions:

1. Players with a permission can fly in lobby (not by using any command, just fly like in gm 1) good for vips
2. /tpv command like on MMC (Players with permission can enable/disable players visibility in lobby)
3. /follow system also like on MMC
4. Also, make so players have to win at least 10 games in order to play ranked. (Number of required wins can be set in config)
5. Add the setting in config when Play Again paper gives, for example in 1 second (players receive it instantly and its not good)

Bugs:

1. My friend found a new bug with book... (Before match starts you take the book from hotbar, click F6 and when match started, you click cancel broadcast and the book won't be removed )**Please, make like on MMC so you can't drag any kit books**
2. Fix ender pearl issue (It can sometimes not being thrown, but cooldown applies)

**Comment by GoodestEnglish** [comment]
In the latest update I just pushed I did some changes to ender pearl and see if the ender pearl not being thrown error still exists or not. If you still encounter the issue. Please record a video with debug mode in Eden and report it. I've also make kit books unable to move in the inventory like you've suggested.

I will add some suggestions you've mentioned, but some will not be added due to time limit
1, 4, and 5 will be added. (Might change)

**Comment by GoodestEnglish** [comment]
Added 5, working on 4

**Comment by GoodestEnglish** [comment]
Added 4 also
