### ISSUE TITLE
Anticheat false flags

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#331]
I've tested Eden with some anticheats and while testing I faced following issues:
False movement flags when teleporting on arena
False movement flags when sumo match starts (it is like player is flying)
False movement flags when players teleports using ender pearl

**Comment by GoodestEnglish** [comment]
What spigot are you using?

**Comment by lenstyy** [comment]
FoxSpigot

**Comment by Chromaah** [comment]
its more like FoxSpigot messing with this stuff, not eden. Also i think i mean that start-freeze sometimes does that?

Last time i tried FoxSpigot (not long ago) it interfered with many plugins and sucked because it had no nms. It also made my anticheat false flag a lot bc of the simplest things.. (falling from high distance, teleporting from/to players and places). If changing the spigot doesnt fix your issue then it might also be your anticheat. Doesnt happen when i dont use foxspigot.

**Comment by GoodestEnglish** [comment]
Agree with what Chromaah said. I would recommend imanity spigot or carbon spigot currently.

Eden simply uses teleport function from bukkit to do teleportation. There's nothing behind the teleportation unless you are using imanity spigot (But since you are not using imanity spigot, this is not the case.
