### ISSUE TITLE
A few more questions

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#37]
1) When is discord suport comming?
2) What are your plans for this plugin?
3) Upcomming features?
4) Are you ever gonna add option weather to reset spawn position after point?
5) Is eden always gonna stay free/open src?

**Comment by HierarchyMan** [comment]
Btw I made working fireball fight (99% accurate replica) with eden
If you want I can show you

**Comment by RealGoodestEnglish** [comment]
Since most of the user wants discord support, I will open one soon.
My plan for this plugin is to add most of the feature I've seen in popular servers such as minemen, lunar into the plugin. 
The next update will be focus on kit transfer from database to yml file first. The next feature is unplanned.
Yes, reset spawn position seems very useful for some kits. This will be added after kit transfer
Yes, Eden will always be open source and free.

**Comment by RealGoodestEnglish** [comment]
Before discord support gets released, I will add github discussions https://github.com/diamond-rip/Eden/discussions to prevent issues spam

If you have any stuff want to ask me, I would recommend to go there!

**Comment by HierarchyMan** [comment]
Amazing
