### ISSUE TITLE
Can attack teammates in party fight using bow and fix ender pearl glitch !!! 

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#527]
While in party split in Bridges players can attack their teammates using bow, i can disable bridges for party split but also would be cool if fixed

And pls fix ender pearl glitch

**Comment by Chromaah** [comment]
Theres a kit gamerule for being able to hit your teammates

**Comment by GoodestEnglish** [comment]
If you want bugs to fix fast like this you should consider to fork the plugin. You are welcome to do this.
As I said before in BBB, the reason why this plugin is open source is because I don't have time to maintain.

This bug is pretty hard to fix since I cannot reproduce and according to bug reporter, the bug happens randomly. I am still working on it.
