### ISSUE TITLE
More 

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#59]
The Event Need More Advanced Things Like 
4Corner And Deathrun
+The Arena Need To Be Fixed Cuz It Don't Randomized Its Just Use The First Map Created
+Need To Support More Spigot Like SpigotX 
+Profile Need To Be Save In YML...

**Comment by HierarchyMan** [comment]
All these features are planned please refrain from spamming and refer to readme

**Comment by Zhuyuan0907** [comment]
> The Event Need More Advanced Things Like 4Corner And Deathrun +The Arena Need To Be Fixed Cuz It Don't Randomized Its Just Use The First Map Created +Need To Support More Spigot Like SpigotX +Profile Need To Be Save In YML...

![image](https://user-images.githubusercontent.com/75146874/211500479-753dea20-6479-4f0b-960b-e41d2cd0f6ca.png)

**Comment by GoodestEnglish** [comment]
Event are def planned but it is not the major currently. We are aiming to fix more bugs first. 
Random arena will be fixed in the next version
SpigotX will not be supported, since the original developer has dropped the support.
Profile will not be saved in yml, because it will break a lot of stuff like statistics tracking
